{
  pkgs,
  env,
  ruby,
}:
[
  env
  ruby
  pkgs.glibc
  pkgs.libyaml
  pkgs.pkg-config
  pkgs.ruby_3_2
  pkgs.rubyPackages_3_2.concurrent-ruby
  pkgs.rubyPackages_3_2.ffi
  pkgs.rubyPackages_3_2.htmlbeautifier
  pkgs.rubyPackages_3_2.nokogiri
  pkgs.rubyPackages_3_2.psych
  pkgs.rubyPackages_3_2.rails
  pkgs.rubyPackages_3_2.rugged
  pkgs.rubyPackages_3_2.tilt
  pkgs.sqlite
]
